### PR TITLE
0.15

### PR DESCRIPTION
**Pull request by bas-ie**
Hello again!

These are the only changes I had to make to enable https://github.com/NoahShomette/bevy_sparse_tilemap/pull/6. For now, I'm dodging the glam/bevy issue! If it turns out to be annoying later, it could always be tweaked. Will finalise this one when 0.15 comes out (hopefully this week?)

### CODE REVIEW

**Comment by NoahShomette** [comment]
Looks good! Just need to swap bevy off the release candidate and then swap back to released hexx version after its released. Thank you very much for doing this!

**Comment by bas-ie** [comment]
`hexx` upgrade is merged, just waiting on a release now.

**Comment by NoahShomette** [comment]
@bas-ie looks like hexx is released. If you update this and bst to the released versions I'll merge and publish asap!

**Comment by bas-ie** [comment]
@NoahShomette I think we're good!

**Review by NoahShomette — APPROVED** [review]

**Comment by NoahShomette** [comment]
> @NoahShomette I think we're good!

Thank you so much for doing this! I will push a release by tonight!

**Pull request merged**
